# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'credits.ui'
#
# Created: Tue Aug  9 23:01:24 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Credits(object):
    def setupUi(self, Credits):
        Credits.setObjectName("Credits")
        Credits.resize(334, 269)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/feedIO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Credits.setWindowIcon(icon)
        self.tabCredits = QtGui.QTabWidget(Credits)
        self.tabCredits.setGeometry(QtCore.QRect(10, 20, 311, 211))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tabCredits.setFont(font)
        self.tabCredits.setObjectName("tabCredits")
        self.Writtenby = QtGui.QWidget()
        self.Writtenby.setObjectName("Writtenby")
        self.label = QtGui.QLabel(self.Writtenby)
        self.label.setGeometry(QtCore.QRect(50, 23, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.Writtenby)
        self.label_2.setGeometry(QtCore.QRect(50, 61, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.Writtenby)
        self.label_3.setGeometry(QtCore.QRect(50, 101, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.Writtenby)
        self.label_4.setGeometry(QtCore.QRect(50, 139, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabCredits.addTab(self.Writtenby, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(54, 24, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(54, 63, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(55, 104, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(55, 142, 191, 21))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabCredits.addTab(self.tab_3, "")
        self.btnClose = QtGui.QPushButton(Credits)
        self.btnClose.setGeometry(QtCore.QRect(231, 238, 91, 27))
        self.btnClose.setObjectName("btnClose")

        self.retranslateUi(Credits)
        self.tabCredits.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Credits)

    def retranslateUi(self, Credits):
        Credits.setWindowTitle(QtGui.QApplication.translate("Credits", "Credits", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Credits", "Chanaka Jayamal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Credits", "Lanka Amarasekara", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Credits", "Kolitha Gajanayake", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Credits", "Chamika Viraj", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCredits.setTabText(self.tabCredits.indexOf(self.Writtenby), QtGui.QApplication.translate("Credits", "Written by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Credits", "Chanaka Jayamal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Credits", "Lanka Amarasekara", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Credits", "Kolitha Gajanayake", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Credits", "Chamika Viraj", None, QtGui.QApplication.UnicodeUTF8))
        self.tabCredits.setTabText(self.tabCredits.indexOf(self.tab_3), QtGui.QApplication.translate("Credits", "Documented by", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClose.setText(QtGui.QApplication.translate("Credits", "&Close", None, QtGui.QApplication.UnicodeUTF8))

import feedIOicons_rc
